ARG BASE_IMAGE="ghcr.io/gbraad-devenv/debian-golang/dotfiles"
ARG BASE_VERSION="bookworm"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/debian-golang"

USER root

ENTRYPOINT ["/sbin/init"]
